export const QUESTIONS = [
  // ─── HISTOIRE ────────────────────────────────────────────────────────────────
  {
    id: 1,
    category: "histoire",
    difficulty: "easy",
    question: "Quel général est devenu le premier Consul de France en 1799 ?",
    answer: "Bonaparte",
    answerType: "name",
    acceptedAnswers: ["Napoleon", "Napoléon"],
    timeLimit: 20,
  },
  {
    id: 2,
    category: "histoire",
    difficulty: "easy",
    question: "En quelle année la Révolution française a-t-elle débuté ?",
    answer: "1789",
    answerType: "date",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 3,
    category: "histoire",
    difficulty: "medium",
    question: "Quelle bataille de 1815 marqua la défaite définitive de Napoléon ?",
    answer: "Waterloo",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 4,
    category: "histoire",
    difficulty: "medium",
    question: "Quel roi de France fut surnommé le Roi-Soleil ?",
    answer: "Louis XIV",
    answerType: "text",
    acceptedAnswers: ["Louis 14", "Louis quatorze"],
    timeLimit: 15,
  },
  {
    id: 5,
    category: "histoire",
    difficulty: "hard",
    question: "En quelle année fut signé le traité de Verdun qui divisa l'empire carolingien ?",
    answer: "843",
    answerType: "date",
    acceptedAnswers: [],
    timeLimit: 10,
  },
  {
    id: 6,
    category: "histoire",
    difficulty: "medium",
    question: "Quelle reine d'Égypte était célèbre pour sa relation avec Jules César et Marc Antoine ?",
    answer: "Cléopâtre",
    answerType: "name",
    acceptedAnswers: ["Cleopatra", "Cleopatre"],
    timeLimit: 15,
  },
  {
    id: 7,
    category: "histoire",
    difficulty: "easy",
    question: "Quel mur, symbole de la Guerre Froide, fut démoli en 1989 ?",
    answer: "Mur de Berlin",
    answerType: "text",
    acceptedAnswers: ["Berlin"],
    timeLimit: 20,
  },
  {
    id: 8,
    category: "histoire",
    difficulty: "hard",
    question: "Quel empire fut fondé par Gengis Khan au XIIIe siècle ?",
    answer: "Empire mongol",
    answerType: "text",
    acceptedAnswers: ["mongol", "empire mongole"],
    timeLimit: 10,
  },
  {
    id: 9,
    category: "histoire",
    difficulty: "medium",
    question: "Lors de quelle guerre la bataille de Verdun a-t-elle eu lieu ?",
    answer: "Première Guerre mondiale",
    answerType: "text",
    acceptedAnswers: ["grande guerre", "premiere guerre mondiale", "1ere guerre mondiale", "WWI", "14-18"],
    timeLimit: 15,
  },
  {
    id: 10,
    category: "histoire",
    difficulty: "hard",
    question: "Quel pharaon fit construire la grande pyramide de Gizeh ?",
    answer: "Khéops",
    answerType: "name",
    acceptedAnswers: ["Kheops", "Cheops", "Khufu"],
    timeLimit: 10,
  },

  // ─── GÉOGRAPHIE ──────────────────────────────────────────────────────────────
  {
    id: 11,
    category: "geographie",
    difficulty: "easy",
    question: "Quelle est la capitale de l'Australie ?",
    answer: "Canberra",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 12,
    category: "geographie",
    difficulty: "easy",
    question: "Quel est le plus long fleuve du monde ?",
    answer: "Nil",
    answerType: "text",
    acceptedAnswers: ["le nil", "amazone"],
    timeLimit: 20,
  },
  {
    id: 13,
    category: "geographie",
    difficulty: "medium",
    question: "Dans quel pays se trouve le Machu Picchu ?",
    answer: "Pérou",
    answerType: "text",
    acceptedAnswers: ["Peru"],
    timeLimit: 15,
  },
  {
    id: 14,
    category: "geographie",
    difficulty: "medium",
    question: "Quel est le plus grand désert du monde ?",
    answer: "Sahara",
    answerType: "text",
    acceptedAnswers: ["antarctique", "désert antarctique"],
    timeLimit: 15,
  },
  {
    id: 15,
    category: "geographie",
    difficulty: "hard",
    question: "Quelle est la capitale du Kazakhstan ?",
    answer: "Astana",
    answerType: "text",
    acceptedAnswers: ["Nur-Sultan", "Noursoultan"],
    timeLimit: 10,
  },
  {
    id: 16,
    category: "geographie",
    difficulty: "easy",
    question: "Sur quel continent se trouve le Brésil ?",
    answer: "Amérique du Sud",
    answerType: "text",
    acceptedAnswers: ["Amerique du sud", "Amérique", "Amerique"],
    timeLimit: 20,
  },
  {
    id: 17,
    category: "geographie",
    difficulty: "medium",
    question: "Quel est le plus haut sommet du monde ?",
    answer: "Everest",
    answerType: "text",
    acceptedAnswers: ["mont everest", "Mount Everest"],
    timeLimit: 15,
  },
  {
    id: 18,
    category: "geographie",
    difficulty: "hard",
    question: "Quel détroit sépare l'Afrique de l'Europe ?",
    answer: "Gibraltar",
    answerType: "text",
    acceptedAnswers: ["détroit de Gibraltar", "detroit de gibraltar"],
    timeLimit: 10,
  },
  {
    id: 19,
    category: "geographie",
    difficulty: "medium",
    question: "Quelle mer borde à la fois l'Espagne, la France et l'Italie ?",
    answer: "Mer Méditerranée",
    answerType: "text",
    acceptedAnswers: ["méditerranée", "mediterranee", "mediterrannee"],
    timeLimit: 15,
  },
  {
    id: 20,
    category: "geographie",
    difficulty: "hard",
    question: "Quelle est la capitale du Bhoutan ?",
    answer: "Thimphou",
    answerType: "text",
    acceptedAnswers: ["Thimbu", "Thimphu", "Thimbu"],
    timeLimit: 10,
  },

  // ─── LITTÉRATURE ─────────────────────────────────────────────────────────────
  {
    id: 21,
    category: "litterature",
    difficulty: "easy",
    question: "Qui a écrit 'Les Misérables' ?",
    answer: "Hugo",
    answerType: "name",
    acceptedAnswers: ["Victor Hugo"],
    timeLimit: 20,
  },
  {
    id: 22,
    category: "litterature",
    difficulty: "easy",
    question: "Dans quel roman de Jules Verne voyage-t-on autour du monde en 80 jours ?",
    answer: "Le Tour du monde en quatre-vingts jours",
    answerType: "text",
    acceptedAnswers: ["tour du monde en 80 jours", "80 jours", "quatre-vingts jours"],
    timeLimit: 20,
  },
  {
    id: 23,
    category: "litterature",
    difficulty: "medium",
    question: "Qui a écrit 'À la recherche du temps perdu' ?",
    answer: "Proust",
    answerType: "name",
    acceptedAnswers: ["Marcel Proust"],
    timeLimit: 15,
  },
  {
    id: 24,
    category: "litterature",
    difficulty: "medium",
    question: "Quel personnage de Molière est obsédé par l'argent ?",
    answer: "Harpagon",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 25,
    category: "litterature",
    difficulty: "hard",
    question: "Qui a écrit 'Le Procès' et 'La Métamorphose' ?",
    answer: "Kafka",
    answerType: "name",
    acceptedAnswers: ["Franz Kafka"],
    timeLimit: 10,
  },
  {
    id: 26,
    category: "litterature",
    difficulty: "easy",
    question: "Qui a écrit 'Harry Potter' ?",
    answer: "Rowling",
    answerType: "name",
    acceptedAnswers: ["J.K. Rowling", "JK Rowling", "Joanne Rowling"],
    timeLimit: 20,
  },
  {
    id: 27,
    category: "litterature",
    difficulty: "medium",
    question: "Dans quel roman d'Albert Camus un homme tue-t-il un Arabe sur une plage d'Algérie ?",
    answer: "L'Étranger",
    answerType: "text",
    acceptedAnswers: ["L'etranger", "Etranger"],
    timeLimit: 15,
  },
  {
    id: 28,
    category: "litterature",
    difficulty: "hard",
    question: "Quel auteur russe a écrit 'Crime et Châtiment' ?",
    answer: "Dostoïevski",
    answerType: "name",
    acceptedAnswers: ["Dostoievski", "Dostoyevski", "Dostoevski", "Fyodor Dostoïevski"],
    timeLimit: 10,
  },
  {
    id: 29,
    category: "litterature",
    difficulty: "medium",
    question: "Quel auteur a créé le personnage de Sherlock Holmes ?",
    answer: "Conan Doyle",
    answerType: "name",
    acceptedAnswers: ["Doyle", "Arthur Conan Doyle"],
    timeLimit: 15,
  },
  {
    id: 30,
    category: "litterature",
    difficulty: "hard",
    question: "Qui a écrit 'Cent ans de solitude' ?",
    answer: "García Márquez",
    answerType: "name",
    acceptedAnswers: ["Garcia Marquez", "Marquez", "Gabriel García Márquez"],
    timeLimit: 10,
  },

  // ─── ART ─────────────────────────────────────────────────────────────────────
  {
    id: 31,
    category: "art",
    difficulty: "easy",
    question: "Qui a peint la Joconde ?",
    answer: "Vinci",
    answerType: "name",
    acceptedAnswers: ["Leonard de Vinci", "Léonard de Vinci", "Leonardo da Vinci", "da Vinci", "Leonardo"],
    timeLimit: 20,
  },
  {
    id: 32,
    category: "art",
    difficulty: "easy",
    question: "Qui a peint 'La Nuit étoilée' ?",
    answer: "Van Gogh",
    answerType: "name",
    acceptedAnswers: ["Vincent Van Gogh", "Vincent van Gogh"],
    timeLimit: 20,
  },
  {
    id: 33,
    category: "art",
    difficulty: "medium",
    question: "Quel artiste espagnol est co-fondateur du cubisme avec Georges Braque ?",
    answer: "Picasso",
    answerType: "name",
    acceptedAnswers: ["Pablo Picasso"],
    timeLimit: 15,
  },
  {
    id: 34,
    category: "art",
    difficulty: "medium",
    question: "Quel architecte a conçu le musée Guggenheim de Bilbao ?",
    answer: "Gehry",
    answerType: "name",
    acceptedAnswers: ["Frank Gehry", "Frank Owen Gehry"],
    timeLimit: 15,
  },
  {
    id: 35,
    category: "art",
    difficulty: "hard",
    question: "Quel peintre flamand du XVIIe siècle est célèbre pour ses autoportraits et son usage du clair-obscur ?",
    answer: "Rembrandt",
    answerType: "name",
    acceptedAnswers: ["Rembrandt van Rijn"],
    timeLimit: 10,
  },
  {
    id: 36,
    category: "art",
    difficulty: "easy",
    question: "Dans quelle ville se trouve le musée du Louvre ?",
    answer: "Paris",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 37,
    category: "art",
    difficulty: "medium",
    question: "Quel artiste surréaliste catalan est célèbre pour ses montres molles ?",
    answer: "Dalí",
    answerType: "name",
    acceptedAnswers: ["Salvador Dali", "Dali", "Salvador Dalí"],
    timeLimit: 15,
  },
  {
    id: 38,
    category: "art",
    difficulty: "hard",
    question: "Qui a sculpté 'Le Penseur' ?",
    answer: "Rodin",
    answerType: "name",
    acceptedAnswers: ["Auguste Rodin"],
    timeLimit: 10,
  },
  {
    id: 39,
    category: "art",
    difficulty: "medium",
    question: "Quel mouvement artistique du XIXe siècle est associé à Claude Monet, Renoir et Degas ?",
    answer: "Impressionnisme",
    answerType: "text",
    acceptedAnswers: ["impressionisme", "l'impressionnisme"],
    timeLimit: 15,
  },
  {
    id: 40,
    category: "art",
    difficulty: "hard",
    question: "Quel peintre néerlandais du XVIIe siècle a réalisé 'La Jeune Fille à la perle' ?",
    answer: "Vermeer",
    answerType: "name",
    acceptedAnswers: ["Johannes Vermeer", "Jan Vermeer"],
    timeLimit: 10,
  },

  // ─── CINÉMA ──────────────────────────────────────────────────────────────────
  {
    id: 41,
    category: "cinema",
    difficulty: "easy",
    question: "Quel film de James Cameron (1997) raconte le naufrage d'un paquebot ?",
    answer: "Titanic",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 42,
    category: "cinema",
    difficulty: "easy",
    question: "Quel acteur joue Iron Man dans le MCU ?",
    answer: "Downey",
    answerType: "name",
    acceptedAnswers: ["Robert Downey Jr", "Robert Downey", "RDJ"],
    timeLimit: 20,
  },
  {
    id: 43,
    category: "cinema",
    difficulty: "medium",
    question: "Quel réalisateur a signé 'Pulp Fiction' et 'Kill Bill' ?",
    answer: "Tarantino",
    answerType: "name",
    acceptedAnswers: ["Quentin Tarantino"],
    timeLimit: 15,
  },
  {
    id: 44,
    category: "cinema",
    difficulty: "medium",
    question: "Dans quel film entend-on la réplique « Je suis ton père » ?",
    answer: "Star Wars",
    answerType: "text",
    acceptedAnswers: ["L'Empire contre-attaque", "empire contre-attaque", "empire strikes back"],
    timeLimit: 15,
  },
  {
    id: 45,
    category: "cinema",
    difficulty: "hard",
    question: "Qui a réalisé '2001, l'Odyssée de l'espace' ?",
    answer: "Kubrick",
    answerType: "name",
    acceptedAnswers: ["Stanley Kubrick"],
    timeLimit: 10,
  },
  {
    id: 46,
    category: "cinema",
    difficulty: "easy",
    question: "Quel film d'animation Pixar met en scène un jeune rat cuisinier à Paris ?",
    answer: "Ratatouille",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 47,
    category: "cinema",
    difficulty: "medium",
    question: "Quel film de Christopher Nolan explore les rêves dans les rêves ?",
    answer: "Inception",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 48,
    category: "cinema",
    difficulty: "hard",
    question: "Quel film japonais de Hayao Miyazaki a remporté l'Oscar du meilleur film d'animation en 2003 ?",
    answer: "Le Voyage de Chihiro",
    answerType: "text",
    acceptedAnswers: ["Spirited Away", "chihiro", "voyage de chihiro"],
    timeLimit: 10,
  },
  {
    id: 49,
    category: "cinema",
    difficulty: "medium",
    question: "Quelle actrice française a joué dans 'Amélie Poulain' ?",
    answer: "Tautou",
    answerType: "name",
    acceptedAnswers: ["Audrey Tautou"],
    timeLimit: 15,
  },
  {
    id: 50,
    category: "cinema",
    difficulty: "hard",
    question: "Quel réalisateur coréen a remporté la Palme d'Or et l'Oscar du meilleur film pour 'Parasite' ?",
    answer: "Bong Joon-ho",
    answerType: "name",
    acceptedAnswers: ["Bong", "Joon-ho", "Bong Joon ho"],
    timeLimit: 10,
  },

  // ─── SPORT ───────────────────────────────────────────────────────────────────
  {
    id: 51,
    category: "sport",
    difficulty: "easy",
    question: "Combien de joueurs composent une équipe de football sur le terrain ?",
    answer: "11",
    answerType: "text",
    acceptedAnswers: ["onze"],
    timeLimit: 20,
  },
  {
    id: 52,
    category: "sport",
    difficulty: "easy",
    question: "Quel pays a remporté la Coupe du Monde de football en 2018 ?",
    answer: "France",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 53,
    category: "sport",
    difficulty: "medium",
    question: "Quel tennisman a remporté le plus grand nombre de titres du Grand Chelem (record historique) ?",
    answer: "Djokovic",
    answerType: "name",
    acceptedAnswers: ["Novak Djokovic", "Nole"],
    timeLimit: 15,
  },
  {
    id: 54,
    category: "sport",
    difficulty: "medium",
    question: "Dans quelle ville ont eu lieu les Jeux Olympiques d'été de 2024 ?",
    answer: "Paris",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 55,
    category: "sport",
    difficulty: "hard",
    question: "Quel athlète jamaïcain détient le record du monde du 100m masculin ?",
    answer: "Bolt",
    answerType: "name",
    acceptedAnswers: ["Usain Bolt"],
    timeLimit: 10,
  },
  {
    id: 56,
    category: "sport",
    difficulty: "easy",
    question: "Quel sport se joue avec un volant (shuttlecock) ?",
    answer: "Badminton",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 57,
    category: "sport",
    difficulty: "medium",
    question: "Combien de sets faut-il remporter pour gagner un match de tennis au Grand Chelem masculin ?",
    answer: "3",
    answerType: "text",
    acceptedAnswers: ["trois"],
    timeLimit: 15,
  },
  {
    id: 58,
    category: "sport",
    difficulty: "hard",
    question: "Quel boxeur américain fut surnommé 'The Greatest' ?",
    answer: "Ali",
    answerType: "name",
    acceptedAnswers: ["Muhammad Ali", "Cassius Clay"],
    timeLimit: 10,
  },
  {
    id: 59,
    category: "sport",
    difficulty: "medium",
    question: "Quel club de football espagnol est surnommé 'les Galactiques' ?",
    answer: "Real Madrid",
    answerType: "text",
    acceptedAnswers: ["Madrid", "le real"],
    timeLimit: 15,
  },
  {
    id: 60,
    category: "sport",
    difficulty: "hard",
    question: "En quelle année les Jeux Olympiques modernes ont-ils été réinstaurés à Athènes ?",
    answer: "1896",
    answerType: "date",
    acceptedAnswers: [],
    timeLimit: 10,
  },

  // ─── BD & MANGA ──────────────────────────────────────────────────────────────
  {
    id: 61,
    category: "bd_manga",
    difficulty: "easy",
    question: "Quel est le vrai nom de Peter Parker ?",
    answer: "Spider-Man",
    answerType: "text",
    acceptedAnswers: ["Spiderman", "Peter Parker"],
    timeLimit: 20,
  },
  {
    id: 62,
    category: "bd_manga",
    difficulty: "easy",
    question: "Quel manga met en scène Naruto Uzumaki, un jeune ninja ?",
    answer: "Naruto",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 63,
    category: "bd_manga",
    difficulty: "medium",
    question: "Qui sont les créateurs de la BD belge Tintin ?",
    answer: "Hergé",
    answerType: "name",
    acceptedAnswers: ["Georges Remi"],
    timeLimit: 15,
  },
  {
    id: 64,
    category: "bd_manga",
    difficulty: "medium",
    question: "Dans quel manga trouve-t-on des Titans géants qui mangent des humains ?",
    answer: "L'Attaque des Titans",
    answerType: "text",
    acceptedAnswers: ["Attack on Titan", "Shingeki no Kyojin", "attaque des titans"],
    timeLimit: 15,
  },
  {
    id: 65,
    category: "bd_manga",
    difficulty: "hard",
    question: "Quel auteur a créé la série de BD 'Blacksad' mettant en scène un chat détective ?",
    answer: "Guarnido",
    answerType: "name",
    acceptedAnswers: ["Juan Díaz Canales", "Canales", "Juanjo Guarnido"],
    timeLimit: 10,
  },
  {
    id: 66,
    category: "bd_manga",
    difficulty: "easy",
    question: "Quel super-héros DC vit à Gotham City et porte une cape noire ?",
    answer: "Batman",
    answerType: "text",
    acceptedAnswers: ["Bruce Wayne"],
    timeLimit: 20,
  },
  {
    id: 67,
    category: "bd_manga",
    difficulty: "medium",
    question: "Qui a créé le manga 'Dragon Ball' ?",
    answer: "Toriyama",
    answerType: "name",
    acceptedAnswers: ["Akira Toriyama"],
    timeLimit: 15,
  },
  {
    id: 68,
    category: "bd_manga",
    difficulty: "hard",
    question: "Dans quel pays la bande dessinée 'Les Aventures de Corentin' de Paul Cuvelier est-elle publiée pour la première fois ?",
    answer: "Belgique",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 10,
  },
  {
    id: 69,
    category: "bd_manga",
    difficulty: "medium",
    question: "Quel manga met en scène Monkey D. Luffy et son équipage de pirates ?",
    answer: "One Piece",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 70,
    category: "bd_manga",
    difficulty: "hard",
    question: "Qui a réalisé le manga 'Berserk' laissé inachevé à sa mort en 2021 ?",
    answer: "Miura",
    answerType: "name",
    acceptedAnswers: ["Kentaro Miura"],
    timeLimit: 10,
  },

  // ─── POLITIQUE ACTUELLE ───────────────────────────────────────────────────────
  {
    id: 71,
    category: "politique",
    difficulty: "easy",
    question: "Qui est le président des États-Unis depuis janvier 2025 ?",
    answer: "Trump",
    answerType: "name",
    acceptedAnswers: ["Donald Trump"],
    timeLimit: 20,
  },
  {
    id: 72,
    category: "politique",
    difficulty: "easy",
    question: "Quel est le titre officiel du chef du gouvernement en France ?",
    answer: "Premier ministre",
    answerType: "text",
    acceptedAnswers: ["premier ministre", "pm"],
    timeLimit: 20,
  },
  {
    id: 73,
    category: "politique",
    difficulty: "medium",
    question: "En quelle année le Royaume-Uni a-t-il officiellement quitté l'Union européenne (Brexit) ?",
    answer: "2020",
    answerType: "date",
    acceptedAnswers: ["2016"],
    timeLimit: 15,
  },
  {
    id: 74,
    category: "politique",
    difficulty: "medium",
    question: "Quelle organisation internationale regroupe les pays les plus industrialisés et économiquement avancés du monde (G7 + Russie) ?",
    answer: "G8",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 75,
    category: "politique",
    difficulty: "hard",
    question: "Quel accord international sur le climat, adopté en 2015, vise à limiter le réchauffement à 1,5°C ?",
    answer: "Accord de Paris",
    answerType: "text",
    acceptedAnswers: ["Paris", "COP21", "accord de paris"],
    timeLimit: 10,
  },
  {
    id: 76,
    category: "politique",
    difficulty: "easy",
    question: "Quelle est la devise de la France ?",
    answer: "Liberté, Égalité, Fraternité",
    answerType: "text",
    acceptedAnswers: ["liberte egalite fraternite", "liberte, egalite, fraternite"],
    timeLimit: 20,
  },
  {
    id: 77,
    category: "politique",
    difficulty: "medium",
    question: "Quel parti politique Emmanuel Macron a-t-il fondé en 2016 ?",
    answer: "La République En Marche",
    answerType: "text",
    acceptedAnswers: ["En Marche", "LREM", "Renaissance"],
    timeLimit: 15,
  },
  {
    id: 78,
    category: "politique",
    difficulty: "hard",
    question: "Quel pays est gouverné par la chancelière qui a succédé à Angela Merkel en 2021 ?",
    answer: "Allemagne",
    answerType: "text",
    acceptedAnswers: ["olaf scholz"],
    timeLimit: 10,
  },
  {
    id: 79,
    category: "politique",
    difficulty: "medium",
    question: "Dans quel pays se trouve le siège de l'ONU à New York ?",
    answer: "États-Unis",
    answerType: "text",
    acceptedAnswers: ["USA", "Etats-Unis", "Etats Unis", "United States"],
    timeLimit: 15,
  },
  {
    id: 80,
    category: "politique",
    difficulty: "hard",
    question: "Quel pays a reconnu l'indépendance du Kosovo en premier parmi les grandes puissances européennes, en 2008 ?",
    answer: "France",
    answerType: "text",
    acceptedAnswers: ["états-unis", "USA"],
    timeLimit: 10,
  },

  // ─── Questions bonus (pour atteindre ~90) ────────────────────────────────────
  {
    id: 81,
    category: "histoire",
    difficulty: "easy",
    question: "Quel explorateur a découvert l'Amérique en 1492 selon la tradition occidentale ?",
    answer: "Christophe Colomb",
    answerType: "name",
    acceptedAnswers: ["Colomb", "Columbus", "Christophe"],
    timeLimit: 20,
  },
  {
    id: 82,
    category: "litterature",
    difficulty: "easy",
    question: "Qui a écrit 'Le Petit Prince' ?",
    answer: "Saint-Exupéry",
    answerType: "name",
    acceptedAnswers: ["Antoine de Saint-Exupéry", "Saint Exupery", "Saint-Exupery"],
    timeLimit: 20,
  },
  {
    id: 83,
    category: "cinema",
    difficulty: "easy",
    question: "Quel film Disney met en scène une princesse aux cheveux dorés enfermée dans une tour ?",
    answer: "Raiponce",
    answerType: "text",
    acceptedAnswers: ["Tangled"],
    timeLimit: 20,
  },
  {
    id: 84,
    category: "geographie",
    difficulty: "easy",
    question: "Quel est le pays le plus grand du monde en superficie ?",
    answer: "Russie",
    answerType: "text",
    acceptedAnswers: ["Russia"],
    timeLimit: 20,
  },
  {
    id: 85,
    category: "sport",
    difficulty: "easy",
    question: "En cyclisme, quel est le maillot porté par le leader du Tour de France ?",
    answer: "Maillot jaune",
    answerType: "text",
    acceptedAnswers: ["jaune"],
    timeLimit: 20,
  },
  {
    id: 86,
    category: "art",
    difficulty: "easy",
    question: "Quel Français a fondé le mouvement du Nouveau Réalisme en 1960 et était connu pour ses monochromes bleus ?",
    answer: "Klein",
    answerType: "name",
    acceptedAnswers: ["Yves Klein"],
    timeLimit: 20,
  },
  {
    id: 87,
    category: "bd_manga",
    difficulty: "easy",
    question: "Quel village gaulois résiste encore et toujours à l'envahisseur romain dans la BD d'Uderzo et Goscinny ?",
    answer: "Astérix",
    answerType: "text",
    acceptedAnswers: ["asterix", "le village d'Astérix"],
    timeLimit: 20,
  },
  {
    id: 88,
    category: "histoire",
    difficulty: "medium",
    question: "Quel président américain a aboli l'esclavage aux États-Unis ?",
    answer: "Lincoln",
    answerType: "name",
    acceptedAnswers: ["Abraham Lincoln"],
    timeLimit: 15,
  },
  {
    id: 89,
    category: "litterature",
    difficulty: "medium",
    question: "Quel roman de George Orwell décrit une société totalitaire sous la surveillance du 'Grand Frère' ?",
    answer: "1984",
    answerType: "text",
    acceptedAnswers: ["nineteen eighty-four", "mil neuf cent quatre-vingt quatre"],
    timeLimit: 15,
  },
  {
    id: 90,
    category: "cinema",
    difficulty: "medium",
    question: "Quel film de Luc Besson (1994) met en scène un tueur professionnel et une jeune fille ?",
    answer: "Léon",
    answerType: "text",
    acceptedAnswers: ["Leon", "Leon le professionnel", "Léon le professionnel"],
    timeLimit: 15,
  },
  {
    id: 91,
    category: "geographie",
    difficulty: "medium",
    question: "Quelle ville est à la fois en Europe et en Asie ?",
    answer: "Istanbul",
    answerType: "text",
    acceptedAnswers: ["Constantinople"],
    timeLimit: 15,
  },
  {
    id: 92,
    category: "politique",
    difficulty: "medium",
    question: "Quel est le nom du Parlement en Israël ?",
    answer: "Knesset",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },

  // ─── HISTOIRE (suite) ─────────────────────────────────────────────────────
  {
    id: 93,
    category: "histoire",
    difficulty: "easy",
    question: "Qui était le premier homme à marcher sur la Lune en 1969 ?",
    answer: "Armstrong",
    answerType: "name",
    acceptedAnswers: ["Neil Armstrong"],
    timeLimit: 20,
  },
  {
    id: 94,
    category: "histoire",
    difficulty: "easy",
    question: "Quel satellite artificiel fut le premier lancé dans l'espace en 1957 ?",
    answer: "Spoutnik",
    answerType: "text",
    acceptedAnswers: ["Sputnik"],
    timeLimit: 20,
  },
  {
    id: 95,
    category: "histoire",
    difficulty: "medium",
    question: "Quel empire dominait l'Amérique du Sud avant l'arrivée des conquistadors espagnols ?",
    answer: "Empire inca",
    answerType: "text",
    acceptedAnswers: ["inca", "les incas", "Inca"],
    timeLimit: 15,
  },
  {
    id: 96,
    category: "histoire",
    difficulty: "medium",
    question: "En quelle année fut signé l'Armistice mettant fin à la Première Guerre mondiale ?",
    answer: "1918",
    answerType: "date",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 97,
    category: "histoire",
    difficulty: "hard",
    question: "Quel traité mit fin à la Guerre de Trente Ans en 1648 ?",
    answer: "Westphalie",
    answerType: "text",
    acceptedAnswers: ["Traité de Westphalie"],
    timeLimit: 10,
  },
  {
    id: 98,
    category: "histoire",
    difficulty: "medium",
    question: "Quelle ville romaine fut détruite par l'éruption du Vésuve en 79 après J.-C. ?",
    answer: "Pompéi",
    answerType: "text",
    acceptedAnswers: ["Pompei", "Herculanum"],
    timeLimit: 15,
  },
  {
    id: 99,
    category: "histoire",
    difficulty: "easy",
    question: "Qui a dirigé l'Allemagne nazie pendant la Seconde Guerre mondiale ?",
    answer: "Hitler",
    answerType: "name",
    acceptedAnswers: ["Adolf Hitler"],
    timeLimit: 20,
  },
  {
    id: 100,
    category: "histoire",
    difficulty: "hard",
    question: "Quel pharaon, dont la tombe fut découverte presque intacte en 1922, est devenu un symbole de l'Égypte antique ?",
    answer: "Toutânkhamon",
    answerType: "name",
    acceptedAnswers: ["Toutankhamun", "Toutankhamon", "Toutankhamoun", "Tutankhamun"],
    timeLimit: 10,
  },
  {
    id: 101,
    category: "histoire",
    difficulty: "medium",
    question: "Quel explorateur portugais fut le premier à circumnaviguer le globe ?",
    answer: "Magellan",
    answerType: "name",
    acceptedAnswers: ["Fernand de Magellan", "Ferdinand Magellan"],
    timeLimit: 15,
  },
  {
    id: 102,
    category: "histoire",
    difficulty: "hard",
    question: "En quelle année le traité de Versailles fut-il signé, mettant officiellement fin à la Première Guerre mondiale ?",
    answer: "1919",
    answerType: "date",
    acceptedAnswers: [],
    timeLimit: 10,
  },

  // ─── GÉOGRAPHIE (suite) ───────────────────────────────────────────────────
  {
    id: 103,
    category: "geographie",
    difficulty: "easy",
    question: "Quelle est la capitale de l'Espagne ?",
    answer: "Madrid",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 104,
    category: "geographie",
    difficulty: "easy",
    question: "Quel est le plus grand océan du monde ?",
    answer: "Pacifique",
    answerType: "text",
    acceptedAnswers: ["Océan Pacifique", "Ocean Pacifique"],
    timeLimit: 20,
  },
  {
    id: 105,
    category: "geographie",
    difficulty: "medium",
    question: "Dans quel pays se trouve la ville de Marrakech ?",
    answer: "Maroc",
    answerType: "text",
    acceptedAnswers: ["Morocco"],
    timeLimit: 15,
  },
  {
    id: 106,
    category: "geographie",
    difficulty: "medium",
    question: "Quel est le plus petit pays du monde en superficie ?",
    answer: "Vatican",
    answerType: "text",
    acceptedAnswers: ["Saint-Siège"],
    timeLimit: 15,
  },
  {
    id: 107,
    category: "geographie",
    difficulty: "hard",
    question: "Quel est le fleuve le plus long d'Europe ?",
    answer: "Volga",
    answerType: "text",
    acceptedAnswers: ["La Volga"],
    timeLimit: 10,
  },
  {
    id: 108,
    category: "geographie",
    difficulty: "easy",
    question: "Combien de continents y a-t-il sur Terre ?",
    answer: "7",
    answerType: "text",
    acceptedAnswers: ["sept"],
    timeLimit: 20,
  },
  {
    id: 109,
    category: "geographie",
    difficulty: "medium",
    question: "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?",
    answer: "Oural",
    answerType: "text",
    acceptedAnswers: ["Monts Oural", "montagnes de l'Oural"],
    timeLimit: 15,
  },
  {
    id: 110,
    category: "geographie",
    difficulty: "hard",
    question: "Quel lac d'Amérique du Sud est considéré comme le lac navigable le plus haut du monde ?",
    answer: "Titicaca",
    answerType: "text",
    acceptedAnswers: ["Lac Titicaca"],
    timeLimit: 10,
  },
  {
    id: 111,
    category: "geographie",
    difficulty: "medium",
    question: "Quelle est la capitale du Canada ?",
    answer: "Ottawa",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 112,
    category: "geographie",
    difficulty: "hard",
    question: "Quel détroit sépare la Sibérie de l'Alaska ?",
    answer: "Béring",
    answerType: "text",
    acceptedAnswers: ["Bering", "Détroit de Béring", "Detroit de Bering"],
    timeLimit: 10,
  },

  // ─── LITTÉRATURE (suite) ──────────────────────────────────────────────────
  {
    id: 113,
    category: "litterature",
    difficulty: "easy",
    question: "Qui a écrit 'Don Quichotte' ?",
    answer: "Cervantes",
    answerType: "name",
    acceptedAnswers: ["Miguel de Cervantes"],
    timeLimit: 20,
  },
  {
    id: 114,
    category: "litterature",
    difficulty: "easy",
    question: "Quel auteur français a écrit 'Le Comte de Monte-Cristo' ?",
    answer: "Dumas",
    answerType: "name",
    acceptedAnswers: ["Alexandre Dumas"],
    timeLimit: 20,
  },
  {
    id: 115,
    category: "litterature",
    difficulty: "medium",
    question: "Dans quel roman de Gustave Flaubert l'héroïne s'appelle Emma Bovary ?",
    answer: "Madame Bovary",
    answerType: "text",
    acceptedAnswers: ["Bovary"],
    timeLimit: 15,
  },
  {
    id: 116,
    category: "litterature",
    difficulty: "medium",
    question: "Qui a écrit 'L'Alchimiste', roman de développement personnel devenu best-seller mondial ?",
    answer: "Coelho",
    answerType: "name",
    acceptedAnswers: ["Paulo Coelho"],
    timeLimit: 15,
  },
  {
    id: 117,
    category: "litterature",
    difficulty: "hard",
    question: "Quel écrivain irlandais a écrit le roman 'Ulysse', publié en 1922 ?",
    answer: "Joyce",
    answerType: "name",
    acceptedAnswers: ["James Joyce"],
    timeLimit: 10,
  },
  {
    id: 118,
    category: "litterature",
    difficulty: "easy",
    question: "Qui a écrit 'Roméo et Juliette' ?",
    answer: "Shakespeare",
    answerType: "name",
    acceptedAnswers: ["William Shakespeare"],
    timeLimit: 20,
  },
  {
    id: 119,
    category: "litterature",
    difficulty: "medium",
    question: "Quel roman d'Aldous Huxley décrit une société dystopique contrôlée par la science ?",
    answer: "Le Meilleur des mondes",
    answerType: "text",
    acceptedAnswers: ["Brave New World", "meilleur des mondes"],
    timeLimit: 15,
  },
  {
    id: 120,
    category: "litterature",
    difficulty: "hard",
    question: "Qui a écrit la pièce de théâtre 'En attendant Godot' ?",
    answer: "Beckett",
    answerType: "name",
    acceptedAnswers: ["Samuel Beckett"],
    timeLimit: 10,
  },
  {
    id: 121,
    category: "litterature",
    difficulty: "medium",
    question: "Quel roman de Stendhal a pour héros Julien Sorel, un jeune homme ambitieux ?",
    answer: "Le Rouge et le Noir",
    answerType: "text",
    acceptedAnswers: ["rouge et le noir", "Le rouge et le noir"],
    timeLimit: 15,
  },
  {
    id: 122,
    category: "litterature",
    difficulty: "hard",
    question: "Quel auteur français a écrit 'La Condition humaine', Prix Goncourt 1933 ?",
    answer: "Malraux",
    answerType: "name",
    acceptedAnswers: ["André Malraux"],
    timeLimit: 10,
  },

  // ─── ART (suite) ──────────────────────────────────────────────────────────
  {
    id: 123,
    category: "art",
    difficulty: "easy",
    question: "Quel artiste américain du Pop Art est célèbre pour ses boîtes de soupe Campbell's ?",
    answer: "Warhol",
    answerType: "name",
    acceptedAnswers: ["Andy Warhol"],
    timeLimit: 20,
  },
  {
    id: 124,
    category: "art",
    difficulty: "easy",
    question: "Dans quelle ville italienne se trouve la chapelle Sixtine ?",
    answer: "Rome",
    answerType: "text",
    acceptedAnswers: ["Vatican"],
    timeLimit: 20,
  },
  {
    id: 125,
    category: "art",
    difficulty: "medium",
    question: "Qui a peint 'Les Demoiselles d'Avignon' ?",
    answer: "Picasso",
    answerType: "name",
    acceptedAnswers: ["Pablo Picasso"],
    timeLimit: 15,
  },
  {
    id: 126,
    category: "art",
    difficulty: "medium",
    question: "Quel architecte américano-chinois a conçu la pyramide de verre du Louvre ?",
    answer: "Pei",
    answerType: "name",
    acceptedAnswers: ["I.M. Pei", "Ieoh Ming Pei", "IM Pei"],
    timeLimit: 15,
  },
  {
    id: 127,
    category: "art",
    difficulty: "hard",
    question: "Quelle artiste mexicaine est célèbre pour ses autoportraits colorés et sa relation avec Diego Rivera ?",
    answer: "Kahlo",
    answerType: "name",
    acceptedAnswers: ["Frida Kahlo"],
    timeLimit: 10,
  },
  {
    id: 128,
    category: "art",
    difficulty: "easy",
    question: "Qui a sculpté la célèbre statue de David exposée à Florence ?",
    answer: "Michel-Ange",
    answerType: "name",
    acceptedAnswers: ["Michelangelo", "Michelange"],
    timeLimit: 20,
  },
  {
    id: 129,
    category: "art",
    difficulty: "medium",
    question: "Quel peintre norvégien a peint 'Le Cri' ?",
    answer: "Munch",
    answerType: "name",
    acceptedAnswers: ["Edvard Munch"],
    timeLimit: 15,
  },
  {
    id: 130,
    category: "art",
    difficulty: "hard",
    question: "Quel peintre grec installé en Espagne est connu sous le surnom de 'El Greco' ?",
    answer: "Le Gréco",
    answerType: "name",
    acceptedAnswers: ["El Greco", "Greco", "Dominikos Theotokopoulos"],
    timeLimit: 10,
  },
  {
    id: 131,
    category: "art",
    difficulty: "medium",
    question: "Dans quelle ville espagnole se trouve le musée du Prado ?",
    answer: "Madrid",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 132,
    category: "art",
    difficulty: "hard",
    question: "Quel artiste britannique contemporain est célèbre pour ses installations de requins dans le formol ?",
    answer: "Hirst",
    answerType: "name",
    acceptedAnswers: ["Damien Hirst"],
    timeLimit: 10,
  },

  // ─── CINÉMA (suite) ───────────────────────────────────────────────────────
  {
    id: 133,
    category: "cinema",
    difficulty: "easy",
    question: "Dans quelle saga de Peter Jackson apparaît le personnage de Gandalf le Gris ?",
    answer: "Le Seigneur des anneaux",
    answerType: "text",
    acceptedAnswers: ["Lord of the Rings", "seigneur des anneaux", "Hobbit"],
    timeLimit: 20,
  },
  {
    id: 134,
    category: "cinema",
    difficulty: "easy",
    question: "Quel acteur joue le capitaine Jack Sparrow dans 'Pirates des Caraïbes' ?",
    answer: "Depp",
    answerType: "name",
    acceptedAnswers: ["Johnny Depp"],
    timeLimit: 20,
  },
  {
    id: 135,
    category: "cinema",
    difficulty: "medium",
    question: "Quel film de Francis Ford Coppola (1972) suit la famille mafieuse Corleone ?",
    answer: "Le Parrain",
    answerType: "text",
    acceptedAnswers: ["Godfather", "parrain", "The Godfather"],
    timeLimit: 15,
  },
  {
    id: 136,
    category: "cinema",
    difficulty: "medium",
    question: "Quel réalisateur a signé à la fois 'Jurassic Park' et 'Schindler's List' ?",
    answer: "Spielberg",
    answerType: "name",
    acceptedAnswers: ["Steven Spielberg"],
    timeLimit: 15,
  },
  {
    id: 137,
    category: "cinema",
    difficulty: "hard",
    question: "Quel film expressionniste allemand de Fritz Lang (1927) décrit une cité futuriste divisée entre élite et travailleurs ?",
    answer: "Metropolis",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 10,
  },
  {
    id: 138,
    category: "cinema",
    difficulty: "easy",
    question: "Dans quel film d'animation Disney Simba est-il le personnage principal ?",
    answer: "Le Roi Lion",
    answerType: "text",
    acceptedAnswers: ["Roi Lion", "Lion King", "The Lion King"],
    timeLimit: 20,
  },
  {
    id: 139,
    category: "cinema",
    difficulty: "medium",
    question: "Quel film de Ridley Scott (1979) a pour slogan 'Dans l'espace, personne ne vous entend crier' ?",
    answer: "Alien",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 140,
    category: "cinema",
    difficulty: "hard",
    question: "Quel acteur a joué Travis Bickle dans 'Taxi Driver' (1976) de Martin Scorsese ?",
    answer: "De Niro",
    answerType: "name",
    acceptedAnswers: ["Robert De Niro", "Robert DeNiro"],
    timeLimit: 10,
  },
  {
    id: 141,
    category: "cinema",
    difficulty: "medium",
    question: "Quel film de Charlie Chaplin (1936) critique la mécanisation du monde ouvrier ?",
    answer: "Les Temps modernes",
    answerType: "text",
    acceptedAnswers: ["Temps modernes", "Modern Times"],
    timeLimit: 15,
  },
  {
    id: 142,
    category: "cinema",
    difficulty: "hard",
    question: "Quel cinéaste suédois a réalisé 'Le Septième Sceau' et 'Persona' ?",
    answer: "Bergman",
    answerType: "name",
    acceptedAnswers: ["Ingmar Bergman"],
    timeLimit: 10,
  },

  // ─── SPORT (suite) ────────────────────────────────────────────────────────
  {
    id: 143,
    category: "sport",
    difficulty: "easy",
    question: "Dans quelle discipline sportive Serena Williams a-t-elle excellé ?",
    answer: "Tennis",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 144,
    category: "sport",
    difficulty: "easy",
    question: "Combien de joueurs composent une équipe de basketball sur le terrain ?",
    answer: "5",
    answerType: "text",
    acceptedAnswers: ["cinq"],
    timeLimit: 20,
  },
  {
    id: 145,
    category: "sport",
    difficulty: "medium",
    question: "Quel pays a remporté le plus de titres de Coupe du Monde de football ?",
    answer: "Brésil",
    answerType: "text",
    acceptedAnswers: ["Brasil", "Brazil"],
    timeLimit: 15,
  },
  {
    id: 146,
    category: "sport",
    difficulty: "medium",
    question: "Quel nageur américain est le sportif le plus médaillé de l'histoire des Jeux Olympiques ?",
    answer: "Phelps",
    answerType: "name",
    acceptedAnswers: ["Michael Phelps"],
    timeLimit: 15,
  },
  {
    id: 147,
    category: "sport",
    difficulty: "hard",
    question: "Quelle est la distance officielle d'un marathon ?",
    answer: "42,195 km",
    answerType: "text",
    acceptedAnswers: ["42 km", "42195 m", "42.195"],
    timeLimit: 10,
  },
  {
    id: 148,
    category: "sport",
    difficulty: "easy",
    question: "Quel sport se joue avec un palet sur une patinoire ?",
    answer: "Hockey sur glace",
    answerType: "text",
    acceptedAnswers: ["hockey"],
    timeLimit: 20,
  },
  {
    id: 149,
    category: "sport",
    difficulty: "medium",
    question: "Quel club de football anglais joue à Anfield et est surnommé 'les Reds' ?",
    answer: "Liverpool",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 150,
    category: "sport",
    difficulty: "hard",
    question: "Quel pilote allemand de Formule 1 a remporté 7 titres mondiaux entre 1994 et 2004 ?",
    answer: "Schumacher",
    answerType: "name",
    acceptedAnswers: ["Michael Schumacher"],
    timeLimit: 10,
  },
  {
    id: 151,
    category: "sport",
    difficulty: "medium",
    question: "Quel pays a remporté la première Coupe du Monde de rugby à XV en 1987 ?",
    answer: "Nouvelle-Zélande",
    answerType: "text",
    acceptedAnswers: ["All Blacks", "New Zealand", "Nouvelle Zelande"],
    timeLimit: 15,
  },
  {
    id: 152,
    category: "sport",
    difficulty: "hard",
    question: "Quel sport de glisse combine ski de fond et tir à la carabine ?",
    answer: "Biathlon",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 10,
  },

  // ─── BD & MANGA (suite) ───────────────────────────────────────────────────
  {
    id: 153,
    category: "bd_manga",
    difficulty: "easy",
    question: "Comment s'appelle le chien blanc de Tintin ?",
    answer: "Milou",
    answerType: "text",
    acceptedAnswers: ["Snowy"],
    timeLimit: 20,
  },
  {
    id: 154,
    category: "bd_manga",
    difficulty: "easy",
    question: "Dans quel manga un lycéen trouve-t-il un carnet permettant de tuer quiconque dont il écrit le nom ?",
    answer: "Death Note",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 20,
  },
  {
    id: 155,
    category: "bd_manga",
    difficulty: "medium",
    question: "Quel manga de Tite Kubo met en scène Ichigo Kurosaki devenant un dieu de la mort (Shinigami) ?",
    answer: "Bleach",
    answerType: "text",
    acceptedAnswers: [],
    timeLimit: 15,
  },
  {
    id: 156,
    category: "bd_manga",
    difficulty: "medium",
    question: "Dans quel manga les frères Edward et Alphonse Elric recherchent-ils la Pierre philosophale ?",
    answer: "Fullmetal Alchemist",
    answerType: "text",
    acceptedAnswers: ["FMA", "Alchimiste", "Full Metal Alchemist"],
    timeLimit: 15,
  },
  {
    id: 157,
    category: "bd_manga",
    difficulty: "hard",
    question: "Quel scénariste belge est à l'origine de la série de BD 'Largo Winch' ?",
    answer: "Van Hamme",
    answerType: "name",
    acceptedAnswers: ["Jean Van Hamme"],
    timeLimit: 10,
  },
  {
    id: 158,
    category: "bd_manga",
    difficulty: "easy",
    question: "Quel super-héros Marvel se transforme en géant vert lorsqu'il est en colère ?",
    answer: "Hulk",
    answerType: "text",
    acceptedAnswers: ["Bruce Banner"],
    timeLimit: 20,
  },
  {
    id: 159,
    category: "bd_manga",
    difficulty: "medium",
    question: "Quel manga met en scène Tanjiro Kamado, un jeune chasseur de démons dans le Japon de l'ère Taisho ?",
    answer: "Demon Slayer",
    answerType: "text",
    acceptedAnswers: ["Kimetsu no Yaiba"],
    timeLimit: 15,
  },
  {
    id: 160,
    category: "bd_manga",
    difficulty: "hard",
    question: "Quel dessinateur franco-belge utilisant l'alias Moebius a co-créé le western 'Blueberry' ?",
    answer: "Giraud",
    answerType: "name",
    acceptedAnswers: ["Jean Giraud", "Moebius"],
    timeLimit: 10,
  },
  {
    id: 161,
    category: "bd_manga",
    difficulty: "medium",
    question: "Quel créateur américain a cofondé Marvel Comics et imaginé Spider-Man, Hulk et les X-Men ?",
    answer: "Stan Lee",
    answerType: "name",
    acceptedAnswers: ["Lee"],
    timeLimit: 15,
  },
  {
    id: 162,
    category: "bd_manga",
    difficulty: "hard",
    question: "Quel auteur de BD belge a créé 'Lucky Luke', le cow-boy qui tire plus vite que son ombre ?",
    answer: "Morris",
    answerType: "name",
    acceptedAnswers: ["Maurice de Bevere", "Maurice De Bevère"],
    timeLimit: 10,
  },

  // ─── POLITIQUE (suite) ────────────────────────────────────────────────────
  {
    id: 163,
    category: "politique",
    difficulty: "easy",
    question: "Combien de membres permanents siègent au Conseil de sécurité de l'ONU ?",
    answer: "5",
    answerType: "text",
    acceptedAnswers: ["cinq"],
    timeLimit: 20,
  },
  {
    id: 164,
    category: "politique",
    difficulty: "easy",
    question: "Quelle est la monnaie commune utilisée dans la zone euro ?",
    answer: "Euro",
    answerType: "text",
    acceptedAnswers: ["€"],
    timeLimit: 20,
  },
  {
    id: 165,
    category: "politique",
    difficulty: "medium",
    question: "Dans quelle ville belge se situent les principales institutions de l'Union européenne ?",
    answer: "Bruxelles",
    answerType: "text",
    acceptedAnswers: ["Brussels", "Bruxelle"],
    timeLimit: 15,
  },
  {
    id: 166,
    category: "politique",
    difficulty: "medium",
    question: "Quel est le nom du président russe en poste depuis 2000 (avec une interruption de 2008 à 2012) ?",
    answer: "Poutine",
    answerType: "name",
    acceptedAnswers: ["Vladimir Poutine", "Putin"],
    timeLimit: 15,
  },
  {
    id: 167,
    category: "politique",
    difficulty: "hard",
    question: "Quel traité européen, signé en 1992, a officiellement créé l'Union européenne ?",
    answer: "Traité de Maastricht",
    answerType: "text",
    acceptedAnswers: ["Maastricht"],
    timeLimit: 10,
  },
  {
    id: 168,
    category: "politique",
    difficulty: "easy",
    question: "Quel pays a organisé ses premières élections démocratiques libres après la fin de l'apartheid en 1994 ?",
    answer: "Afrique du Sud",
    answerType: "text",
    acceptedAnswers: ["South Africa"],
    timeLimit: 20,
  },
  {
    id: 169,
    category: "politique",
    difficulty: "medium",
    question: "Quel est le nom de l'alliance militaire regroupant les pays d'Europe de l'Ouest et d'Amérique du Nord, fondée en 1949 ?",
    answer: "OTAN",
    answerType: "text",
    acceptedAnswers: ["NATO", "Alliance Atlantique", "Organisation du Traité de l'Atlantique Nord"],
    timeLimit: 15,
  },
  {
    id: 170,
    category: "politique",
    difficulty: "hard",
    question: "Quel homme politique sud-africain a reçu le Prix Nobel de la Paix en 1993 après avoir lutté contre l'apartheid ?",
    answer: "Mandela",
    answerType: "name",
    acceptedAnswers: ["Nelson Mandela"],
    timeLimit: 10,
  },
  {
    id: 171,
    category: "politique",
    difficulty: "medium",
    question: "Quel parti politique dirige la République populaire de Chine depuis 1949 ?",
    answer: "Parti communiste chinois",
    answerType: "text",
    acceptedAnswers: ["PCC", "communiste", "parti communiste", "CPC"],
    timeLimit: 15,
  },
  {
    id: 172,
    category: "politique",
    difficulty: "hard",
    question: "Dans quel pays se trouve la Cour internationale de Justice, principale instance judiciaire de l'ONU ?",
    answer: "Pays-Bas",
    answerType: "text",
    acceptedAnswers: ["Hollande", "La Haye", "Netherlands"],
    timeLimit: 10,
  },
];
